[package]
name = "rust-rv-embedded-template"
version = "0.1.0"
authors = ["Liangdi <wu@liangdi.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
panic-halt = "0.2.0"
riscv-rt = "0.8.0"
